-- MySQL Script generated by MySQL Workbench
-- Tue Dec 17 08:34:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema vasto_verde
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vasto_verde
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vasto_verde` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tiposUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tiposUsuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`associacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`associacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoas` (
  `idPessoa` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `idTipoUsuario` INT NOT NULL,
  `idAssociacao` INT NULL,
  PRIMARY KEY (`idPessoa`, `idTipoUsuario`, `idAssociacao`),
  INDEX `fk_pessoas_tiposUsuarios1_idx` (`idTipoUsuario` ASC) VISIBLE,
  INDEX `fk_pessoas_associacao1_idx` (`idAssociacao` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_tiposUsuarios1`
    FOREIGN KEY (`idTipoUsuario`)
    REFERENCES `mydb`.`tiposUsuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_associacao1`
    FOREIGN KEY (`idAssociacao`)
    REFERENCES `mydb`.`associacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grau` (
  `id` INT NOT NULL,
  `grau` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoasCompetitivas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoasCompetitivas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `federacao` INT NULL,
  `confederacao` INT NULL,
  `dataInicio` VARCHAR(10) NOT NULL,
  `idPessoa` INT NOT NULL,
  `idGrau` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`, `idGrau`),
  INDEX `fk_pessoasCompetitivas_pessoas1_idx` (`idPessoa` ASC) VISIBLE,
  INDEX `fk_pessoasCompetitivas_grau1_idx` (`idGrau` ASC) VISIBLE,
  CONSTRAINT `fk_pessoasCompetitivas_pessoas`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `mydb`.`pessoas` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoasCompetitivas_grau1`
    FOREIGN KEY (`idGrau`)
    REFERENCES `mydb`.`grau` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`professores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cref` INT NULL,
  `idPessoaCompetitiva` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoaCompetitiva`),
  INDEX `fk_professores_pessoaCompetitiva1_idx` (`idPessoaCompetitiva` ASC) VISIBLE,
  CONSTRAINT `fk_professores_pessoaCompetitiva1`
    FOREIGN KEY (`idPessoaCompetitiva`)
    REFERENCES `mydb`.`pessoasCompetitivas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idAssociacao` INT NOT NULL,
  PRIMARY KEY (`id`, `idAssociacao`),
  INDEX `fk_eventos_associacao1_idx` (`idAssociacao` ASC) VISIBLE,
  CONSTRAINT `fk_eventos_associacao1`
    FOREIGN KEY (`idAssociacao`)
    REFERENCES `mydb`.`associacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sugestoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sugestoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sugestao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoasSugestoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoasSugestoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoas_idPessoa` INT NOT NULL,
  `pessoas_idTipoUsuario` INT NOT NULL,
  PRIMARY KEY (`id`, `pessoas_idPessoa`, `pessoas_idTipoUsuario`),
  INDEX `fk_pessoas_has_sugestoes_sugestoes1_idx` (`id` ASC) VISIBLE,
  INDEX `fk_pessoas_has_sugestoes_pessoas1_idx` (`pessoas_idPessoa` ASC, `pessoas_idTipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_has_sugestoes_pessoas1`
    FOREIGN KEY (`pessoas_idPessoa` , `pessoas_idTipoUsuario`)
    REFERENCES `mydb`.`pessoas` (`idPessoa` , `idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_has_sugestoes_sugestoes1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`sugestoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoasEventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoasEventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `eventos_id` INT NOT NULL,
  `pessoas_idPessoa` INT NOT NULL,
  PRIMARY KEY (`id`, `eventos_id`, `pessoas_idPessoa`),
  INDEX `fk_eventos_has_pessoas_pessoas1_idx` (`pessoas_idPessoa` ASC) VISIBLE,
  INDEX `fk_eventos_has_pessoas_eventos1_idx` (`eventos_id` ASC) VISIBLE,
  CONSTRAINT `fk_eventos_has_pessoas_eventos1`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `mydb`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_has_pessoas_pessoas1`
    FOREIGN KEY (`pessoas_idPessoa`)
    REFERENCES `mydb`.`pessoas` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vasto_verde` ;

-- -----------------------------------------------------
-- Table `vasto_verde`.`graus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`graus` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cor` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vasto_verde`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`tipousuario` (
  `id` INT(11) NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vasto_verde`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`pessoas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `tipoUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `tipoUsuario`),
  INDEX `fk_pessoas_tipoUsuario1_idx` (`tipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_tipoUsuario`
    FOREIGN KEY (`tipoUsuario`)
    REFERENCES `vasto_verde`.`tipousuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = '	';


-- -----------------------------------------------------
-- Table `vasto_verde`.`atletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`atletas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeResponsavel` VARCHAR(40) NOT NULL,
  `dataInicio` VARCHAR(10) NOT NULL,
  `federacao` INT(5) NULL DEFAULT NULL,
  `condeferacao` INT(5) NULL DEFAULT NULL,
  `idPessoa` INT(11) NOT NULL,
  `idGrau` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`, `idGrau`),
  INDEX `fk_atletas_pessoas_idx` (`idPessoa` ASC) VISIBLE,
  INDEX `fk_atletas_graus1_idx` (`idGrau` ASC) VISIBLE,
  CONSTRAINT `fk_atletas_graus`
    FOREIGN KEY (`idGrau`)
    REFERENCES `vasto_verde`.`graus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atletas_pessoas`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `vasto_verde`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
