-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 20:05:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoUsuario` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `tipoUsuario` INT NOT NULL,
  PRIMARY KEY (`id`, `tipoUsuario`),
  INDEX `fk_pessoas_tipoUsuario1_idx` (`tipoUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_tipoUsuario`
    FOREIGN KEY (`tipoUsuario`)
    REFERENCES `mydb`.`tipoUsuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`graus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`graus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cor` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atletas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeResponsavel` VARCHAR(40) NOT NULL,
  `dataInicio` VARCHAR(10) NOT NULL,
  `federacao` INT(5) NULL,
  `condeferacao` INT(5) NULL,
  `idPessoa` INT NOT NULL,
  `idGrau` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`, `idGrau`),
  INDEX `fk_atletas_pessoas_idx` (`idPessoa` ASC) VISIBLE,
  INDEX `fk_atletas_graus1_idx` (`idGrau` ASC) VISIBLE,
  CONSTRAINT `fk_atletas_pessoas`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `mydb`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atletas_graus`
    FOREIGN KEY (`idGrau`)
    REFERENCES `mydb`.`graus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
