-- MySQL Script generated by MySQL Workbench
-- Tue Dec 17 09:50:30 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vasto_verde
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vasto_verde
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vasto_verde` DEFAULT CHARACTER SET utf8 ;
USE `vasto_verde` ;

-- -----------------------------------------------------
-- Table `vasto_verde`.`associacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`associacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vasto_verde`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`pessoas` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `tipoUsuario` INT NOT NULL,
  `idAssociacao` INT NULL,
  PRIMARY KEY (`idPessoa`),
  INDEX `fk_pessoas_associacao1_idx` (`idAssociacao` ASC) ,
  CONSTRAINT `fk_pessoas_associacao1`
    FOREIGN KEY (`idAssociacao`)
    REFERENCES `vasto_verde`.`associacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vasto_verde`.`grau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`grau` (
  `id` INT NOT NULL,
  `grau` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vasto_verde`.`pessoasCompetitivas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`pessoasCompetitivas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `federacao` INT NULL,
  `confederacao` INT NULL,
  `dataInicio` VARCHAR(10) NOT NULL,
  `idPessoa` INT NOT NULL,
  `idGrau` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoa`, `idGrau`),
  INDEX `fk_pessoasCompetitivas_pessoas1_idx` (`idPessoa` ASC) ,
  INDEX `fk_pessoasCompetitivas_grau1_idx` (`idGrau` ASC) ,
  CONSTRAINT `fk_pessoasCompetitivas_pessoas`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `vasto_verde`.`pessoas` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoasCompetitivas_grau1`
    FOREIGN KEY (`idGrau`)
    REFERENCES `vasto_verde`.`grau` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vasto_verde`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`professores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cref` INT NULL,
  `idPessoaCompetitiva` INT NOT NULL,
  PRIMARY KEY (`id`, `idPessoaCompetitiva`),
  INDEX `fk_professores_pessoaCompetitiva1_idx` (`idPessoaCompetitiva` ASC) ,
  CONSTRAINT `fk_professores_pessoaCompetitiva1`
    FOREIGN KEY (`idPessoaCompetitiva`)
    REFERENCES `vasto_verde`.`pessoasCompetitivas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vasto_verde`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`eventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(10) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idAssociacao` INT NOT NULL,
  PRIMARY KEY (`id`, `idAssociacao`),
  INDEX `fk_eventos_associacao1_idx` (`idAssociacao` ASC) ,
  CONSTRAINT `fk_eventos_associacao1`
    FOREIGN KEY (`idAssociacao`)
    REFERENCES `vasto_verde`.`associacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vasto_verde`.`sugestoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`sugestoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sugestao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vasto_verde`.`pessoasSugestoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`pessoasSugestoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoas_idPessoa` INT NOT NULL,
  `pessoas_idSugestao` INT NOT NULL,
  PRIMARY KEY (`id`, `pessoas_idPessoa`, `pessoas_idSugestao`),
  INDEX `fk_pessoas_has_sugestoes_pessoas1_idx` (`pessoas_idPessoa` ASC) ,
  INDEX `fk_pessoas_has_sugestoes_sugestoes1_idx` (`pessoas_idSugestao` ASC) ,
  CONSTRAINT `fk_pessoas_has_sugestoes_pessoas`
    FOREIGN KEY (`pessoas_idPessoa`)
    REFERENCES `vasto_verde`.`pessoas` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_has_sugestoes_sugestoes1`
    FOREIGN KEY (`pessoas_idSugestao`)
    REFERENCES `vasto_verde`.`sugestoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vasto_verde`.`pessoasEventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vasto_verde`.`pessoasEventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `eventos_id` INT NOT NULL,
  `pessoas_idPessoa` INT NOT NULL,
  PRIMARY KEY (`id`, `eventos_id`, `pessoas_idPessoa`),
  INDEX `fk_eventos_has_pessoas_pessoas1_idx` (`pessoas_idPessoa` ASC) ,
  INDEX `fk_eventos_has_pessoas_eventos1_idx` (`eventos_id` ASC) ,
  CONSTRAINT `fk_eventos_has_pessoas_eventos1`
    FOREIGN KEY (`eventos_id`)
    REFERENCES `vasto_verde`.`eventos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_has_pessoas_pessoas1`
    FOREIGN KEY (`pessoas_idPessoa`)
    REFERENCES `vasto_verde`.`pessoas` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
